### PR TITLE
Allow to use a non-default cozy-controller port

### LINKED ISSUE #154: Changing cozy-controller port
Hi,

Cozy-controller port seems to be easily changed by passing it an env variable `PORT=XXX`. In my case it is mandatory as I already have a service running on the default 9002 port, which I cannot move to another port.

But Cozy-monitor hardcodes the port of Cozy-controller, and fails afterwards.

As far as I understand, this is [this line](https://github.com/cozy/cozy-monitor/blob/7ef0132743406900d25c60b845e339e0a31b2ae3/src/helpers.coffee#L17) which could be replaced by
```
controllerPort = process.env.CONTROLLER_PORT or '9002'
```
and use of this variable.

Thanks

### PR DESCRIPTION
**Pull request by Phyks**
This change introduces a `CONTROLLER_PORT` env variable to pass a
non-default port to use to talk to cozy-controller.

Closes #154.

### CODE REVIEW

**Comment by Phyks** [comment]
Updated commit to remove `controllerUrl` which was not used anytime across the app and allow to pass a `CONTROLLER_PORT` to change the port to use to communicate with cozy-controller.

Also, one should use `CONTROLLER_PORT` when starting cozy-controller to pass it a different port, and not `PORT` which would be inherited by any launched apps.

**Comment by nono** [comment]
@aenario can you look at this PR?

**Comment by aenario** [comment]
Hi @Phyks, we wont be merging this PR as your changes in cozy-clients have the same effect, instead I just made a PR to update cozy-clients ( https://github.com/cozy/cozy-monitor/pull/158 )

Note that in order to solve the initial issue on home, the same changes (update of cozy-clients) will need to be applied there too. Can you handle it?

**Comment by Phyks** [comment]
Sure

**Pull request closed without merging**
