### PR TITLE
Enable build for node 4/5

### PR DESCRIPTION
**Pull request by nono**
Travis build was red

### CODE REVIEW

**Comment by nono** [comment]
It needs a new release of cozy-home with this fix: https://github.com/cozy/cozy-home/pull/647

**Comment by aenario** [comment]
Restarting travis build as cozy/cozy-home#647 was merged.

**Comment by nono** [comment]
Still the 'Token is not correct' error :/

**Comment by nono** [comment]
@aenario yeah, the build is green :dancers:

**Comment by aenario** [comment]
Ok, everything looks good code-wise.

We usually dont bother with it, but just this once, would you mind squashing all the debug / add debug / remove debug commits into one ?

**Comment by nono** [comment]
I've made another PR with debug commits squashed: #123

**Pull request closed without merging**
